### ISSUE TITLE
wrong logic

### ISSUE THREAD

**Issue by kimfom01** [mbashit/mathexpressionexercise2ii#1]
Remember the relationship between indices and roots where square root of x is equal to x to the power of 1/2? 
![image](https://user-images.githubusercontent.com/57032138/183773069-4ef7a6a4-25a5-42d7-bf3f-a1d78d658f62.png)
Same applies here, in this question we have to find the 5th root of an expression so the inbuilt functions only let you find square root and not 5th root but with the knowledge of the relationship between roots and indices we can compute the 5th root by finding the power raised to 1/5.
Also be careful with your BODMAS thinking else you will get wrong results.

``` diff
#include <iostream>
#include <cmath>

using namespace std;

int main()
{
    double x, y;
    cout << "enter the value of x";
    cin >> x;

-    y = 5 * sqrt(3 * pow(x, 2) - 1 / 4 * pow(x, 3));
+    y = pow(3 * pow(x, 2) - ((1.0 / 4) * pow(x, 3)), 1/5);
     cout << "the result is " << y << endl;
     return 0;
}
```

**Comment by mbashit** [comment]
Errors noted and corrected.

**Comment by kimfom01** [comment]
> Errors noted and corrected.

don't forget to commit and push
